# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f75df262ab6e1cd1763c9797c00d7769"
application_url = "https://b524-193-194-127-249.ngrok-free.app"
embedded = true
name = "form-customer"
handle = "form-customer"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[app_proxy]
url = "https://b524-193-194-127-249.ngrok-free.app/app/proxy"
subpath = "forms"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://b524-193-194-127-249.ngrok-free.app/auth/callback",
  "https://b524-193-194-127-249.ngrok-free.app/auth/shopify/callback",
  "https://b524-193-194-127-249.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "learn123456.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
